### ISSUE TITLE
Feature Request: Specify location of local manga

### ISSUE THREAD

**Issue by Andrewpaps** [faldez/tanoshi#284]
Would be handy specify where to scan for local files instead of having to use the installation location only.

**Comment by faldez** [comment]
you already can specify location of local manga, just change `local_path` in `config.yml`

for single directory you specify 
```
local_paht:  /path/to/local
```

for multiple directories
```
local_path:
- name: Local1
  path: /path/to/local1
- name: Local2
  path: /path/to/local2
```
