### ISSUE TITLE
[Help please]

### ISSUE THREAD

**Issue by IagoMega** [faldez/tanoshi#53]
first thank so much i really like your project but can you make a guide of How to install... i'm two weeks trying to install this but nothing at now.
i'm frustrated

I really want to use tanoshi.

**Comment by faldez** [comment]
Hi @IagoMega, I'm sorry for late respond and the inconvenience. I realize the installation is kinda confusing now. It's still work in progress to streamlined the installation process.

May be I can provide official docker

**Comment by faldez** [comment]
I switch to SQLite on v0.5.0 so you don't need any external software, but I only test tanoshi on mac and linux platform since I don't have any access to windows

**Comment by eridanired123** [comment]
At the moment of writing this comment, you can do it by following these steps:

1. Download `tanoshi-linux`  from the releases page (or the one for your OS), plus the plugins following the readme.md instructions of this repository.
2. Place them into a folder with this structure:

```
    MyTanoshiFolder
      |--- tanoshi-linux
      |--- config.yml
      |--- plugins
          |--- liblocal.so
          |--- libmangadex.so
          |--- libmangasee.so
```

3. Edit `config.yml` with a text editor (do not use word processors), paste the example from the readme.md and edit these lines to point to the correct routes:

```
     base_url: http://PUT_THE_URL_HERE:3030

     database_path: /PATH/TO/YOUR/MyTanoshiFolder/database
     # The database will be created by tanoshi on first run inside MyTanoshiFolder and will be named "database"

     plugin_path: /PATH/TO/YOUR/MyTanoshiFolder/plugins
     plugin_config:
     # Plugin name
       local:
          path: /PATH/TO/YOUR/MANGA/
```
4. Then you start tanoshi by using this command: `./tanoshi-linux --config /PATH/TO/YOUR/MyTanoshiFolder/config.yml`. tanoshi is supposed to look for this file automatically in a default path, but it didn't find it in my case and had to explicitly tell tanoshi where to look for it.
5. Finally open the address you put above in the address bar of your web browser; this address is usually your PC's IP address or device name on your local network appended by the port number, `:3030` in this example. If you don't know it, you can use `localhost:3030`, `127.0.0.1:3030` or `0.0.0.0:3030` in most cases.
